# Generated by Django 4.2.11 on 2024-04-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('avatar', models.TextField(null=True)),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('company', models.TextField()),
                ('license', models.TextField()),
                ('bus_number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=models.UUIDField(), primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('avatar', models.TextField(null=True)),
                ('date_of_birth', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Parent',
            },
        ),
    ]
