# Generated by Django 4.2.9 on 2024-02-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=1024, verbose_name='Video URL')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='Transcription')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='Upload Time')),
                ('transcription_time', models.DateTimeField(blank=True, null=True, verbose_name='Transcription Completed Time')),
            ],
        ),
    ]
