# Generated by Django 4.2.11 on 2024-04-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='driver',
            table='Driver',
        ),
    ]
