# Generated by Django 4.2.9 on 2024-02-16 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('src', '0002_videotranscription_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotranscription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_transcriptions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
